let errorLog = {}

let promise = new Promise((resolve, reject) => {
   
}, function(){
	 throw new Error('Something failed');
})